import { test, expect, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";

const source = Buffer.from('R7,FICTIONAL-A,,"1.25,-2",Top,90,SYNTHETIC\nR7,FICTIONAL-B,,"0,0",Bottom,0,SYNTHETIC\n');
const file = { name: 'fictional-session.csv', mimeType: 'text/csv', buffer: source };
const nav = (page: Page, name: string) => page.getByRole('navigation', { name: 'SCAN screens' }).getByRole('link', { name, exact: true });
async function read(page: Page) {
  await page.getByRole('button', { name: 'Read file', exact: true }).click();
  await expect(page.getByText('2 source rows', { exact: false })).toBeVisible();
}
async function validate(page: Page) {
  await page.getByLabel('Module for this sheet').fill('FICTIONAL-MODULE');
  await page.getByLabel('Placement units').selectOption('inch');
  await page.getByLabel('Source rotation direction').selectOption('cw');
  await page.getByRole('button', { name: 'Validate placements' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Placement parsing complete' })).toBeVisible();
}

test('one source session survives dashboard, workspace, findings and browser history', async ({ page, baseURL }, testInfo) => {
  const errors: string[] = [], external: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('request', request => { if (new URL(request.url()).origin !== baseURL) external.push(request.url()); });
  await page.goto('/');
  await page.getByRole('link', { name: 'Open placement intake', exact: true }).click();
  await page.getByLabel('Placement file (.xlsx, .xls or .csv)', { exact: true }).setInputFiles(file);
  await read(page); await validate(page);
  await nav(page, 'Job dashboard').click();
  await expect(page.getByRole('region', { name: 'Placement source', exact: true })).toContainText(file.name);
  await expect(page.getByRole('status', { name: 'Placement session status' })).toHaveText('Placement parsing complete');
  await expect(page.getByRole('region', { name: 'Coverage states' }).getByLabel('Represented: unknown', { exact: true })).toHaveText('—');
  await expect(page.getByRole('button', { name: 'Export machine job', exact: true })).toBeDisabled();
  const pendingDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Save placement record (JSON)' }).click();
  const download = await pendingDownload;
  const record = JSON.parse(await readFile((await download.path())!, 'utf8'));
  expect(record.placements).toHaveLength(2);
  expect(record.placements[0].xMm).toBe('31.750');
  expect(record.machineExportAllowed).toBe(false);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('connected-dashboard.png'), fullPage: true });
  await nav(page, 'Board workspace').click();
  await page.getByLabel('Placement to inspect').selectOption('1');
  const selected = page.getByRole('region', { name: 'Selected placement', exact: true });
  await expect(selected).toContainText('FICTIONAL-MODULE / Top / R7');
  await expect(selected).toContainText('31.750');
  await page.getByLabel('Placement to inspect').selectOption('2');
  await expect(selected).toContainText('FICTIONAL-MODULE / Bottom / R7');
  await expect(selected).not.toContainText('FICTIONAL-A');
  await selected.getByText('Placement and source identity', { exact: true }).click();
  await expect(selected).toContainText(record.placements[1].placementId);
  await expect(selected).toContainText(record.sourceSha256);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('connected-workspace.png'), fullPage: true });
  await nav(page, 'Source findings').click();
  await expect(page.getByText('No row issues were reported by the placement parser.')).toBeVisible();
  await page.goBack();
  await expect(page.getByLabel('Placement to inspect')).toHaveValue('2');
  await page.goForward();
  await page.getByRole('link', { name: 'Edit source mapping', exact: true }).click();
  await expect(page.getByLabel('Module for this sheet')).toHaveValue('FICTIONAL-MODULE');
  await expect(page.getByLabel('Placement units')).toHaveValue('inch');
  await expect(page.getByRole('button', { name: 'Read file', exact: true })).toBeEnabled();
  await expect(page.getByRole('heading', { name: '3. Placement review' })).toBeVisible();
  await page.getByRole('button', { name: 'Read file', exact: true }).click();
  await expect(page.getByText('2 source rows', { exact: false })).toBeVisible();
  await expect(page.getByLabel('Placement units')).toHaveValue('inch');
  await nav(page, 'Board workspace').click();
  await expect(page.getByRole('heading', { name: 'Validate a placement source first' })).toBeVisible();
  await expect(page.getByRole('main')).toHaveCount(1);
  await expect(page.locator('[aria-current="page"]')).toHaveCount(1);
  expect(errors).toEqual([]); expect(external).toEqual([]);
});

test('mapping, delimiter, sheet and file edits invalidate all dependent views', async ({ page }) => {
  await page.goto('/intake');
  await page.getByLabel('Placement file').setInputFiles(file);
  await read(page); await validate(page);
  await nav(page, 'Board workspace').click();
  await page.getByLabel('Placement to inspect').selectOption('2');
  await nav(page, 'Source intake').click();
  await page.getByLabel('Placement units').selectOption('mm');
  await nav(page, 'Board workspace').click();
  await expect(page.getByLabel('Placement to inspect')).toHaveCount(0);
  await nav(page, 'Job dashboard').click();
  await expect(page.getByRole('button', { name: 'Save placement record (JSON)' })).toBeDisabled();
  await nav(page, 'Source findings').click();
  await expect(page.getByRole('heading', { name: 'No placement review yet' })).toBeVisible();
  await nav(page, 'Source intake').click();
  await validate(page);
  await nav(page, 'Board workspace').click();
  await expect(page.getByLabel('Placement to inspect')).toHaveValue('');
  await nav(page, 'Source intake').click();
  await page.getByLabel('CSV delimiter').selectOption(';');
  await expect(page.getByRole('button', { name: 'Validate placements' })).toHaveCount(0);
  await page.getByLabel('CSV delimiter').selectOption(',');
  await read(page); await validate(page);
  await page.getByLabel('Worksheet index').fill('1');
  await expect(page.getByRole('button', { name: 'Validate placements' })).toHaveCount(0);
  await page.getByLabel('Worksheet index').fill('0');
  await read(page); await validate(page);
  await page.getByLabel('Placement file').setInputFiles({ ...file, name: 'other-fictional.csv' });
  await nav(page, 'Job dashboard').click();
  await expect(page.getByRole('status', { name: 'Placement session status' })).toHaveText('Ready to read');
  await page.getByRole('button', { name: 'Clear session', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Placement session status' })).toHaveText('No source loaded');
  await nav(page, 'Source intake').click();
  await expect(page.getByRole('button', { name: 'Read file', exact: true })).toBeDisabled();
  await page.getByLabel('Placement file').setInputFiles(file);
  await read(page); await validate(page);
  await nav(page, 'Board workspace').click();
  await expect(page).toHaveURL('/workspace');
  await expect(page.getByLabel('Placement to inspect')).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Validate a placement source first' })).toBeVisible();
  await nav(page, 'Source findings').click();
  await expect(page.getByRole('heading', { name: 'No placement review yet' })).toBeVisible();
});

test('clear from dashboard rejects an in-flight response across navigation', async ({ page }) => {
  let release!: () => void, received!: () => void, delivered!: () => void;
  const held = new Promise<void>(resolve => { release = resolve; });
  const arrived = new Promise<void>(resolve => { received = resolve; });
  const finished = new Promise<void>(resolve => { delivered = resolve; });
  await page.route('**/api/placements', async route => {
    const response = await route.fetch(); received();
    await held;
    try { await route.fulfill({ response }); } catch { /* Browser may already have aborted. */ }
    delivered();
  });
  await page.goto('/intake');
  await page.getByLabel('Placement file').setInputFiles(file);
  await page.getByRole('button', { name: 'Read file', exact: true }).click();
  await arrived;
  await nav(page, 'Job dashboard').click();
  await expect(page.getByRole('status', { name: 'Placement session status' })).toHaveText('Processing source');
  await page.getByRole('button', { name: 'Clear session', exact: true }).click();
  release(); await finished;
  await nav(page, 'Source intake').click();
  await expect(page.getByRole('button', { name: 'Read file', exact: true })).toBeDisabled();
  await expect(page.getByRole('heading', { name: '2. Confirm mapping and conventions' })).toHaveCount(0);
  await expect(page.getByRole('main').getByRole('alert')).toHaveCount(0);
  await page.unroute('**/api/placements');
  await page.getByLabel('Placement file').setInputFiles(file);
  await read(page);
});

test('blocked duplicate identities retain distinct source rows in workspace', async ({ page }, testInfo) => {
  await page.goto('/intake');
  await page.getByLabel('Placement file').setInputFiles({ ...file, buffer: Buffer.from('R7,FIRST,,"1,2",Top,0,SYNTHETIC\nR7,SECOND,,"3,4",Top,0,SYNTHETIC\n') });
  await read(page);
  await page.getByLabel('Module for this sheet').fill('FICTIONAL-MODULE');
  await page.getByLabel('Placement units').selectOption('mm');
  await page.getByLabel('Source rotation direction').selectOption('ccw');
  await page.getByRole('button', { name: 'Validate placements' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Placement review needs attention' })).toBeVisible();
  await nav(page, 'Source findings').click();
  await expect(page.getByRole('region', { name: 'Placement source review' })).toContainText('Row 2');
  await page.screenshot({ path: testInfo.outputPath('connected-findings.png'), fullPage: true });
  await nav(page, 'Board workspace').click();
  await expect(page.getByRole('status').filter({ hasText: 'unresolved holds' })).toBeVisible();
  await page.getByLabel('Placement to inspect').selectOption('1');
  await expect(page.getByRole('region', { name: 'Selected placement', exact: true })).toContainText('FIRST');
  await page.getByLabel('Placement to inspect').selectOption('2');
  await expect(page.getByRole('region', { name: 'Selected placement', exact: true })).toContainText('SECOND');
  await nav(page, 'Job dashboard').click();
  await expect(page.getByRole('button', { name: 'Save placement record (JSON)' })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Export machine job', exact: true })).toBeDisabled();
});
