import { test, expect, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";
const nav = (page: Page, name: string) => page.getByRole('navigation', { name: 'SCAN screens' }).getByRole('link', { name, exact: true });
const csv = 'A1,FICTIONAL,,"0,0",Top,0,SYNTHETIC\nA2,FICTIONAL,,"10,0",Top,0,SYNTHETIC\nA3,FICTIONAL,,"0,20",Top,0,SYNTHETIC\nA4,FICTIONAL,,"7,11",Top,0,SYNTHETIC\n';
const gerber = '%MOMM*%\n%FSLAX23Y23*%\n%ADD10C,1*%\nD10*\nX100000Y50000D03*\nX100000Y60000D03*\nX80000Y50000D03*\nX89000Y57000D03*\nX89001Y57001D01*\nM02*\n';

test('Gerber reviewed interpretation, rigid fit, held-out check, handoff and stale-control invalidation', async ({ page, baseURL }, info) => {
  const errors: string[] = [], external: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (new URL(r.url()).origin !== baseURL) external.push(r.url()); });
  await page.goto('/intake');
  await page.getByLabel('Placement file').setInputFiles({ name: 'fictional.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) });
  await page.getByRole('button', { name: 'Read file', exact: true }).click();
  await page.getByLabel('Module for this sheet').fill('Fictional-A');
  await page.getByLabel('Placement units').selectOption('mm');
  await page.getByLabel('Source rotation direction').selectOption('ccw');
  await page.getByRole('button', { name: 'Validate placements' }).click();
  await expect(page.getByText('4 parsed · 0 errors', { exact: false })).toBeVisible();
  await page.getByLabel('Gerber file').setInputFiles({ name: 'fictional.gbx', mimeType: 'text/plain', buffer: Buffer.from(gerber) });
  await page.getByRole('button', { name: 'Read Gerber', exact: true }).click();
  await expect(page.getByText('coordinate token exceeds declared FS width')).toBeVisible();
  await page.getByText('Review an incorrect source declaration', { exact: true }).click();
  await page.getByLabel('Coordinate format override').selectOption('FSLAX33Y33');
  await page.getByLabel('I have reviewed the source').check();
  await page.getByRole('button', { name: 'Read Gerber', exact: true }).click();
  await expect(page.getByText('Gerber geometry parsed', { exact: true })).toBeVisible();
  await nav(page, 'Board workspace').click();
  await page.getByLabel('Placement module and side').selectOption('["Fictional-A","Top"]');
  await page.getByLabel('Gerber board instance').fill('Authored board one');
  const controls = [[0,0,100,50],[10,0,100,60],[0,20,80,50],[7,11,89.2,57]];
  for (const [i,p] of controls.entries()) {
    for (const [n,label] of ['CAD X','CAD Y','Gerber X','Gerber Y'].entries()) await page.getByLabel(`${label} mm · point ${i+1}`, { exact: true }).fill(String(p[n]));
    await page.getByLabel(`Physical match evidence · point ${i+1}`).fill(`Independently authored feature ${i+1}`);
  }
  await page.getByRole('button', { name: 'Fit and check alignment' }).click();
  await expect(page.getByRole('heading', { name: 'Alignment needs review — diagnostic overlay only' })).toBeVisible();
  await page.getByLabel('Gerber X mm · point 4', { exact: true }).fill('89');
  await page.getByRole('button', { name: 'Fit and check alignment' }).click();
  await expect(page.getByRole('heading', { name: 'Alignment checks passed' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('gerber-alignment.png'), fullPage: true });
  await nav(page, 'Job dashboard').click();
  await expect(page.getByText('Control-point checks passed')).toBeVisible();
  await nav(page, 'Source findings').click();
  await expect(page.getByText('Alignment control checks passed for the recorded module, side and board instance.')).toBeVisible();
  await nav(page, 'Review handoff').click();
  const pending = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download complete review (.json)' }).click();
  const saved = JSON.parse(await readFile((await (await pending).path())!, 'utf8'));
  expect(saved.alignment.status).toBe('success'); expect(saved.gerber.objects).toHaveLength(5); expect(saved.machineExportAllowed).toBe(false);
  expect(saved.alignment.basis).toContain('normalizedHash');
  const draftPending = page.waitForEvent('download'); await page.getByRole('button', { name: 'Save review', exact: true }).click();
  const draftPath = (await (await draftPending).path())!; const draft = JSON.parse(await readFile(draftPath, 'utf8'));
  expect(draft.artifactType).toBe('scan.source-review-session'); expect(draft.gerber.checked).toBe(true);
  await page.reload();
  await page.getByLabel('Saved placement review file').setInputFiles(draftPath);
  await expect(page.getByText('Review reopened.', { exact: false })).toBeVisible();
  await nav(page, 'Board workspace').click();
  await expect(page.getByRole('heading', { name: 'Alignment checks passed' })).toBeVisible();
  await page.getByLabel('Saved placement review file').setInputFiles({ name: 'corrupt.json', mimeType: 'application/json', buffer: Buffer.from('{}') });
  await expect(page.getByText('Unexpected or missing review fields.')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Alignment checks passed' })).toBeVisible();
  await nav(page, 'Source intake').click();
  await page.getByLabel('Coordinate format override').selectOption('FSLAX34Y34');
  await page.getByRole('button', { name: 'Read Gerber', exact: true }).click();
  await expect(page.getByText('Gerber geometry parsed', { exact: true })).toBeVisible();
  await nav(page, 'Board workspace').click();
  await expect(page.getByLabel('CAD X mm · point 1', { exact: true })).toHaveValue('');
  await expect(page.getByLabel('Gerber X mm · point 1', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: 'Fit and check alignment' }).click();
  await expect(page.getByText('Enter every control coordinate and tolerance as a plain number in millimeters.')).toBeVisible();
  const badScope = structuredClone(draft); badScope.gerber.scope.module = 'Does-not-exist';
  await page.getByLabel('Saved placement review file').setInputFiles({ name: 'bad-scope.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(badScope)) });
  await expect(page.getByText('Review reopened.', { exact: false })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Alignment checks passed' })).toHaveCount(0);
  await nav(page, 'Source intake').click();
  await expect(page.getByText('Saved alignment scope needs a module and side with confirmed placement units.')).toBeVisible();
  const badSheet = structuredClone(draft); badSheet.placement.sheetIndex = 19;
  await page.getByLabel('Saved placement review file').setInputFiles({ name: 'bad-sheet.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(badSheet)) });
  await expect(page.getByText('Saved source and notes restored, but parsing failed.', { exact: false })).toBeVisible();
  await expect(page.getByText('Gerber geometry parsed', { exact: true })).toBeVisible();
  let release!: () => void; let reached!: () => void;
  const held = new Promise<void>(resolve => { release = resolve; }); const started = new Promise<void>(resolve => { reached = resolve; });
  await page.route('**/api/placements', async route => { reached(); await held; await route.continue(); });
  await page.getByLabel('Saved placement review file').setInputFiles(draftPath); await started;
  await page.getByLabel('Gerber file').setInputFiles({ name: 'new-choice.gbr', mimeType: 'text/plain', buffer: Buffer.from('%MOMM*%\n%FSLAX24Y24*%\n%ADD10C,1*%\nD10*\nX0Y0D03*\nM02*') });
  await page.getByRole('button', { name: 'Read Gerber', exact: true }).click();
  await expect(page.getByText('1 apertures · 1 objects', { exact: false })).toBeVisible();
  release(); await expect(page.getByText('Review reopened.', { exact: false })).toBeVisible();
  await expect(page.getByText('1 apertures · 1 objects', { exact: false })).toBeVisible();
  await page.unroute('**/api/placements');
  expect(errors).toEqual([]); expect(external).toEqual([]);
});

test('geometry endpoints enforce origin and reject invalid settings', async ({ request, baseURL }) => {
  for (const endpoint of ['/api/gerber','/api/alignment']) expect((await request.post(endpoint, { data: '{}' })).status()).toBe(403);
  const parsed = await request.post('/api/gerber', { headers: { Origin: baseURL! }, multipart: { file: { name: 'invalid.gbr', mimeType: 'text/plain', buffer: Buffer.from(gerber) }, config: JSON.stringify({ formatOverride: 33, assumeLinear: true }) } });
  expect((await parsed.json()).status).toBe('blocked');
  const invalid = await request.post('/api/alignment', { headers: { Origin: baseURL!, 'Content-Type': 'application/json' }, data: {} });
  expect((await invalid.json()).status).toBe('blocked');
});
