export type BomConfig = { headerRow: number; columns: Record<"quantity" | "refdes" | "value" | "description" | "manufacturer" | "mpn" | "footprint", number>; scope: { module: string; side: string; boardInstance: string }; revision: string; variant: string };
export const initialBomConfig = (): BomConfig => ({ headerRow: 1, columns: { quantity: 1, refdes: 2, value: 3, description: 4, manufacturer: 5, mpn: 6, footprint: 7 }, scope: { module: "", side: "", boardInstance: "" }, revision: "", variant: "" });
export type BomReference = { sourceRow: number; rawRefdes: string; normalizedRefdes: string; rawGroupRefdes: string; rawMpn: unknown; rawValue: unknown; mpn: string | null; populationEvidence: string; scope: BomConfig["scope"]; workOrderPopulation: "unapproved"; quantityMatches: boolean };
export type BomResult = { artifactType: "scan.engineering-bom"; status: "success" | "blocked"; sourceSha256: string; sheetIndex: number; worksheet: string; config: BomConfig; headers: unknown[]; preview: unknown[][]; groups: { sourceRow: number; raw: Record<string, unknown>; references: string[]; quantity: number | null; quantityMatches: boolean; populationEvidence: string; mpnInterpretation: string; interpretedMpn: string | null }[]; references: BomReference[]; issues: { row: number; severity: string; code: string; message: string }[]; counts: { groups: number; expandedReferences: number; uniqueReferences: number; quantityTotal: number; engineeringDnpReferences: number }; workOrderPopulation: "unapproved"; machineExportAllowed: false };
export function validateBomConfig(value: unknown): BomConfig {
  const c = value as BomConfig;
  if (!c || typeof c !== "object" || Object.keys(c).sort().join() !== "columns,headerRow,revision,scope,variant" || !Number.isInteger(c.headerRow) || c.headerRow < 1 || c.headerRow > 10000 || !c.columns || Object.keys(c.columns).sort().join() !== "description,footprint,manufacturer,mpn,quantity,refdes,value" || Object.values(c.columns).some(v => !Number.isInteger(v) || v < 1 || v > 64) || !c.scope || Object.keys(c.scope).sort().join() !== "boardInstance,module,side" || [...Object.values(c.scope), c.revision, c.variant].some(v => typeof v !== "string" || v.length > 256 || v.includes("\0"))) throw new Error("Invalid saved BOM mapping.");
  if (new Set(Object.values(c.columns)).size !== 7) throw new Error("BOM columns must be distinct.");
  return c;
}
